### ISSUE TITLE
.htaccess rule breaks image rendering

### ISSUE THREAD

**Issue by jonathanphz** [jkphl/squeezr#15]
Hi - great tool, but I'm having a problem. I'm optimizing a site for a client, they used Codeigniter, when I combine your .htaccess none of the images load on the page.

Troubleshooting it I found that this is the line that is causing it:
RewriteRule ^(.+)(.(?:jpe?g|gif|png))$ squeezr/cache/$1-%1$2 [NC,E=BREAKPOINT:%1,L]

Do you have any suggestions??

Thanks!

More info: the only thing on my .htaccess is:
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]

followed by your .htaccess rules

I'm working locally using Mamp.

**Comment by jkphl** [comment]
Hi @jonathanphz,

thanks for your report. I'm sorry but I can hardly support your case, as I have no idea of Codeigniter and the specific setup. However, the line

```
RewriteRule ^(.*)$ /index.php/$1 [L]
```

is supposed to redirect **all** requests (for files that don't physically exist) to `index.php`. Putting the *squeezr* rules **after** this line will effectively prevent *squeezr* from working. Please try to understand how `.htaccess` respectively `mod_rewrite` works. I'm not sure if this is the solution for your problem, but please try to insert the *squeezr* rules directly after `RewriteBase /` and let me know if this works for you.

Cheers,
Joschi

**Comment by jonathanphz** [comment]
Ok I inserted the squeezr rules after RewriteBase/:

Background images now display but the ones in <img> tags are not showing up. Gonna try other things and see if I can solve it.

Thanks for the response.

**Comment by jkphl** [comment]
@jonathanphz I'm just about doing a brush up of squeezr's codebase and was wondering if you still have these issues? Since you didn't reply for a long time I'll close this issue for now, but please feel free to get back in touch if you still experience any problems. Thanks!
