### ISSUE TITLE
Demo failed in Chrome 55 due to CORS

### ISSUE THREAD

**Issue by jkphl** [jkphl/squeezr#18]
See https://twitter.com/fakecarlsagan/status/812352872209928192:
> Demo failed for me in Chrome 55 due to CORS. Probably not fixable.

**Comment by jkphl** [comment]
Spent some time on *squeezr* today and started adding a test suite (dev branch only at the moment) but I cannot reproduce any errors with Chrome 55 and CORS. Is anyone able to provide some details?

**Comment by rspeed** [comment]
Attempting to use the demo with the URL "https://www.ultravioletflowersdc.com" fails silently. The only feedback is this error appearing in the console:

`XMLHttpRequest cannot load https://squeezr.it/test-drive/?random=1483552584532. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://squeezr.it' is therefore not allowed access.`

**Comment by jkphl** [comment]
@rspeed Ok, this clears things up a bit. So you aren't talking about the demo included in the *squeezr* package itself but rather about the test drive on the [squeezr.it](https://squeezr.it) website, correct? But anyway, I cannot reproduce this either, unfortunately:

![ultravioletflowersdc](https://cloud.githubusercontent.com/assets/4446936/21653466/94cf495e-d2b1-11e6-9850-523122d59887.png)

Are you using any special settings on your browser? Which platform are you on?

**Comment by rspeed** [comment]
That's so weird. No special settings, I get the same result from a completely fresh browser. Running on macOS 10.12.2 (though the same issue appeared in 10.12.1). It works fine in Firefox 50.

**Comment by jkphl** [comment]
@rspeed Weird indeed! But maybe the difference is that I'm on Windows / Linux (and unfortunately don't have a Mac OS handy right now).

What I'm just stumbling upon: The error message states that

> `http://squeezr.it` is not allowed access to `https://squeezr.it/test-drive/...`.

Do you notice the missing `s`? How come that you're able to visit the HTTP site (instead of HTTPS) while there should be a general redirect? Could you try using the HTTPS site and run the test drive then again? Thanks!

**Comment by rspeed** [comment]
That did the trick! There definitely isn't a redirect, though.

```console
$ curl -I http://squeezr.it
HTTP/1.1 200 OK
Date: Wed, 04 Jan 2017 18:48:04 GMT
Server: Apache/2.4.25
Strict-Transport-Security: max-age=15768000
Content-Type: text/html; charset=UTF-8
```

**Comment by rspeed** [comment]
And now I feel stupid for not even thinking to check that when I recognized the CORS issue.

**Comment by jkphl** [comment]
@rspeed Haha, cool! Then it's probably just me routinely typing `https` instead of `http`. :D 
In any case, now there **IS** a redirect. ;) Thanks for helping me solve this. Glad it works for you now!
